### ISSUE TITLE
不如直接允许在 canvas 上绘制

### ISSUE THREAD

**Issue by inkydragon** [ProjectYanbao/1stTeamBuilding#1]
分解成三原色再画感觉好奇怪。

能直接操作 canvas 还能利用一下现成的函数，感觉会更好上手一些。

例如有教程
https://airingursb.gitbooks.io/canvas/content/

----

另外这个感觉是难度有点高的。
限定成海龟画图看起来也不错，python 版 https://python123.io/index/turtles/latest

**Comment by 7sDream** [comment]
其实用三原色这种比较适合画和位置成函数关续的，偏数学或者几何学的图像（比如分形之类），可能这也是目的吧。印象里这种趣味比赛还挺多的。

如果用 canvas 的话，大家说不定就 `getContext('webgl')` 然后用 webGL 去了……

**Comment by inkydragon** [comment]
> 大家说不定就 `getContext('webgl')` 然后用 webGL 去了

也不是不行嘛。

想要限制用什么技术，直接写在说明里就好了，反正是靠自觉。

我想的是直接用 canvas。然后能画直线、bezier1-3、椭圆，然后找个 SVG 暴力生成代码。

----

偏数学的函数画图，加上时间会更好一些。就可以上傅里叶套娃画图了。

类似这种 https://tixy.land/

**Comment by gonlyk** [comment]
根本没法时间，循环太多直接卡死
